Rails.application.routes.draw do
 root to: 'pages#home'
 get 'about', to: 'pages#about'
 get 'history', to: 'pages#history'
 get 'pastoral', to: 'pages#pastoral'
 get 'becomingAnglican', to: 'pages#becomingAnglican'
 get 'returningToChurch', to: 'pages#returningToChurch'
 get 'whyAnglican', to: 'pages#whyAnglican'
 get 'athletics', to: 'pages#athletics'
 get 'childrenMinistry', to: 'pages#childrenMinistry'
 get 'combineService', to: 'pages#combineService'
 get 'evangelism', to: 'pages#evangelism'
 get 'faithClinic', to: 'pages#faithClinic'
 get 'firstService', to: 'pages#firstService'
 get 'foundationBibleClass', to: 'pages#foundationBibleClass'
 get 'hospitalVisitation', to: 'pages#hospitalVisitation'
 get 'jobs', to: 'pages#jobs'
 get 'news', to: 'pages#news'
 get 'onlinGiving', to: 'pages#onlinGiving'
 get 'otherService', to: 'pages#otherService'
 get 'prisonVisitation', to: 'pages#prisonVisitation'
 get 'schoolOfMinistry', to: 'pages#schoolOfMinistry'
 get 'secondService', to: 'pages#secondService'
 get 'sundayBulletin', to: 'pages#sundayBulletin'
 get 'teenageMinistry', to: 'pages#teenageMinistry'
 get 'todaysReading', to: 'pages#todaysReading'
 get 'welfare', to: 'pages#welfare'
 get 'youthMinistry', to: 'pages#youthMinistry'
 end
